[package]
name = "rust-fundamentals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
rand = "0.8.5"
unicode-segmentation = "1.10.1"
